[package]
name = "hello-world-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.hello-world]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.58.0"
default-features = false
