// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   8

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    auction
    (
        init => init
        upgrade => upgrade
        createAuction => create_auction
        placeBid => place_bid
        finalizeAuction => finalize_auction
        cancelAuction => cancel_auction
        getAuctionInfo => get_auction_info
        getActiveAuctions => get_active_auctions
        getTimeRemaining => get_time_remaining
        canFinalize => can_finalize
    )
}